/**
 * Characterization tests.
 *
 * golden.json was generated by running the ORIGINAL pre-refactor
 * implementation (the pure functions that used to live in src/App.js) over
 * every case in cases.json. These tests assert the extracted modules still
 * produce byte-identical output, so the Phase 0 refactor cannot silently
 * change anyone's numbers.
 *
 * These pin CURRENT behaviour, including behaviour we intend to improve
 * later — see the "known behaviour" tests at the bottom.
 */
import cases from '../__fixtures__/cases.json';
import golden from '../__fixtures__/golden.json';
import { calculateHealthScore, getScoreRating, getImprovementTips } from '../healthScore';
import {
  calculateStrategy,
  calculateMultipleDebts,
  calculateRecommendedPayment,
  filterValidDebts,
  PAYOFF_HORIZON_MONTHS,
} from '../planner/debt';

describe('calculateHealthScore', () => {
  Object.entries(cases.profiles).forEach(([name, profile]) => {
    it(`matches the original output for the "${name}" profile`, () => {
      expect(calculateHealthScore(profile)).toEqual(golden.healthScore[name]);
    });
  });
});

describe('getScoreRating', () => {
  cases.scores.forEach((score) => {
    it(`matches the original rating at a score of ${score}`, () => {
      expect(getScoreRating(score)).toEqual(golden.scoreRating[String(score)]);
    });
  });
});

describe('getImprovementTips', () => {
  Object.entries(cases.profiles).forEach(([name, profile]) => {
    const expected = golden.improvementTips[name];
    if (expected === null) return; // no score, so no tips to compare
    it(`matches the original tips for the "${name}" profile`, () => {
      expect(getImprovementTips(calculateHealthScore(profile))).toEqual(expected);
    });
  });
});

describe('calculateRecommendedPayment', () => {
  Object.entries(cases.debtSets).forEach(([debtName, debts]) => {
    const valid = filterValidDebts(debts);
    const totalDebt = valid.reduce((sum, d) => sum + parseFloat(d.balance), 0);
    const totalMin = valid.reduce((sum, d) => sum + parseFloat(d.minPayment), 0);

    Object.entries(cases.profiles).forEach(([profileName, profile]) => {
      it(`matches the original for ${debtName} + ${profileName}`, () => {
        expect(calculateRecommendedPayment(profile, totalDebt, totalMin)).toEqual(
          golden.recommendedPayment[`${debtName}|${profileName}`]
        );
      });
    });
  });
});

describe('calculateStrategy', () => {
  Object.entries(cases.debtSets).forEach(([debtName, debts]) => {
    const valid = filterValidDebts(debts);
    if (!valid.length) return;

    [0, 100, 500].forEach((extra) => {
      ['avalanche', 'snowball'].forEach((strategy) => {
        it(`matches the original for ${debtName} @ $${extra} extra, ${strategy}`, () => {
          expect(calculateStrategy([...valid], extra, strategy)).toEqual(
            golden.strategy[`${debtName}|${extra}|${strategy}`]
          );
        });
      });
    });
  });
});

describe('calculateMultipleDebts', () => {
  Object.entries(cases.debtSets).forEach(([debtName, debts]) => {
    cases.extraPayments.forEach((extra) => {
      it(`matches the original for ${debtName} @ extra "${extra}" with no profile`, () => {
        expect(calculateMultipleDebts(debts, extra, null)).toEqual(
          golden.multipleDebts[`${debtName}|${extra}|null`]
        );
      });

      ['typical', 'deficit', 'zeroIncome', 'highEarnerNoDebt'].forEach((profileName) => {
        it(`matches the original for ${debtName} @ extra "${extra}" with ${profileName}`, () => {
          expect(calculateMultipleDebts(debts, extra, cases.profiles[profileName])).toEqual(
            golden.multipleDebts[`${debtName}|${extra}|${profileName}`]
          );
        });
      });
    });

    it(`matches the original for ${debtName} with a null extra payment`, () => {
      expect(calculateMultipleDebts(debts, null, null)).toEqual(
        golden.multipleDebts[`${debtName}|__null__|null`]
      );
    });
  });

  it('returns null when handed no debt list at all', () => {
    expect(calculateMultipleDebts(undefined, null, null)).toBeNull();
    expect(calculateMultipleDebts(undefined, null, null)).toEqual(golden.multipleDebts.__undefinedList__);
  });
});

describe('known behaviour worth remembering', () => {
  it('does not mutate the caller\'s debt objects', () => {
    const debts = JSON.parse(JSON.stringify(cases.debtSets.three));
    const before = JSON.stringify(debts);
    calculateMultipleDebts(debts, '250', cases.profiles.typical);
    expect(JSON.stringify(debts)).toEqual(before);
  });

  it('stops at the horizon when a minimum payment never covers the interest', () => {
    // A $20k balance at 29.99% accrues ~$500/mo of interest against a $50
    // minimum, so this debt is never repaid. The simulation caps out rather
    // than looping forever; surfacing that to the user is Phase 1 work.
    const result = calculateStrategy([...cases.debtSets.minPaymentBelowInterest], 0, 'avalanche');
    expect(result.months).toBe(PAYOFF_HORIZON_MONTHS);
  });

  it('ignores rows the user has not filled in', () => {
    const result = calculateMultipleDebts(cases.debtSets.partiallyInvalid, '100', null);
    expect(result.debts).toHaveLength(1);
    expect(result.totalDebt).toBe(4000);
  });
});
